movielens/accounts/urls.py
from django.conf.urls import url, include
from . import views
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm

app_name = 'accounts'

urlpatterns = [

    # url(r'^register/',
        # CreateView.as_view(template_name='registration/register.html',
                        #    form_class=UserCreationForm,
                        #    success_url='/'),
        # name='register'),
    # url(r'^$', include('django.contrib.auth.urls')),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^logout_success/$', views.logout_success, name='logout_success'),
    url(r'^register/$', views.register, name='register'),
    url(r'^', include('registration.backends.simple.urls')),
    ]

movielens/movielens/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView

app_name = 'home'

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/ratings/', permanent=False),
        name='redirect'),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^ratings/', include('ratings.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls'))
]

movielens/ratings/urls.py
from django.conf.urls import url
from . import views

app_name = 'ratings'

urlpatterns = [

    url(r'^$', views.home, name='home'),
    # url(r'^(?P<name>\w+)/$', views.index, name='page'),
    url(r'^movies/$', views.movie_index, name='movie_index'),
    url(r'^movies/(?P<movie>[0-9]+)$', views.movie_detail,
        name='movie_detail'),
    url(r'^raters/$', views.rater_index, name='rater_index'),
    url(r'^raters/(?P<rater>[0-9]+)$', views.rater_detail,
        name='rater_detail'),
    url(r'^top/$', views.top_rated, name="top_rated"),
    url(r'^movies/search/$', views.movie_index, name='movie_search')
]

movielens/ratings/models.py
from django.db import models
from django.db.models import Avg, Count
from django.contrib.auth.models import User


class Movie(models.Model):
    title = models.CharField(max_length=200)
    release = models.DateField()
    url = models.CharField(max_length=200, default="N/A")
    avg_rating = models.DecimalField(decimal_places=2, max_digits=3, default=0)
    total_ratings = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def get_average(self):
        return Rating.objects.filter(movie_id=self.id).aggregate(Avg('score'))

    def get_total(self):
        ratings = Rating.objects.filter(movie_id=self.id)
        return ratings.aggregate(Count('score'))

    @staticmethod
    def get_top(num=20):
        ratings_list = []
        for movie in Movie.objects.all():
            if movie.total_ratings > 100:
                ratings_list.append((movie.id, movie.avg_rating))
        ratings_list = sorted(ratings_list, key=lambda movie: movie[1],
                              reverse=True)
        top_rated = []
        for i in ratings_list:
            top_rated.append(Movie.objects.get(id=i[0]))
        return top_rated[:num]


class Rater(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    age = models.IntegerField(default=0)
    sex = models.CharField(max_length=200, default="")
    occupation = models.CharField(max_length=200, default="")
    avg_rating = models.DecimalField(decimal_places=2, max_digits=3, default=0)
    total_ratings = models.IntegerField(default=0)

    def __str__(self):
        return ("{}: {} {} {}".format(self.id, self.age, self.sex,
                                      self.occupation))

    def get_average_rating(self):
        return Rating.objects.filter(rater_id=self.id).aggregate(Avg('score'))

    def get_total(self):
        rating = Rating.objects.filter(rater_id=self.id)
        return rating.aggregate(Count('score'))


class Rating(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    movie_name = models.CharField(max_length=200)
    score = models.IntegerField(default=0)
    rater = models.ForeignKey(Rater, on_delete=models.CASCADE)

    def __str__(self):
        return ("{}: {} by {}".format(self.movie,
                                      self.score, self.rater))

    def get_movie_name(self):
        movie = Movie.objects.get(id=self.movie_id)
        return movie.title

movielens/ratings/forms.py
from django import forms


class SearchForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('title', 'release', 'url')

movielens/ratings/views.py
from django.shortcuts import render, get_object_or_404
from .models import Movie, Rater, Rating


def home(request):
    pages = ['movies', 'raters', 'top']
    context = {'is_authenticated': request.user.is_authenticated(),
               'pages': pages}
    return render(request, 'ratings/home.html', context)


def movie_index(request):
    search = False
    all_movies = Movie.objects.all().order_by('title')
    movie_cols = ['Title', 'Average Rating', 'URL']
    context = {'all_movies': all_movies, 'columns': movie_cols,
               'is_authenticated': request.user.is_authenticated()}
    if 'q' in request.GET and request.GET['q']:
        search = True
        q = request.GET['q']
        movies = Movie.objects.filter(title__icontains=q)
        message = 'You searched for: %r' % request.GET['q']
        context = {'message': message, 'query': q,
                   'movies': movies.order_by('title'),
                   'all_movies': all_movies.order_by('title'),
                   'columns': movie_cols,
                   'is_authenticated': request.user.is_authenticated(),
                   'search': search}
    return render(request, 'ratings/movie_index.html', context)


def rater_index(request):
    raters = Rater.objects.all()
    context = {'is_authenticated': request.user.is_authenticated(),
               'raters': raters, 'columns': ['ID', 'Age', 'Sex',
                                             'Occupation', 'Movies Rated']}
    return render(request, 'ratings/rater_index.html', context)


def top_rated(request):
    top_rated = Movie.get_top()
    movie_cols = ['Rank', 'Title', 'Average Rating',
                  'Total Ratings', 'URL']
    context = {'is_authenticated': request.user.is_authenticated(),
               'top_rated': top_rated, 'columns': movie_cols}
    return render(request, 'ratings/top_rated.html', context)


def movie_detail(request, movie):
    movie = get_object_or_404(Movie, id=movie)
    ratings = Rating.objects.filter(movie_id=movie)
    context = {'is_authenticated': request.user.is_authenticated(),
               'movie': movie, 'ratings': ratings}
    return render(request, 'ratings/movie_detail.html', context)


def rater_detail(request, rater):
    rater = get_object_or_404(Rater, id=rater)
    ratings = Rating.objects.filter(rater_id=rater)
    context = {'is_authenticated': request.user.is_authenticated(),
               'rater': rater, 'ratings': ratings}
    return render(request, 'ratings/rater_detail.html', context)

movielens/ratings/templates/ratings/home.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Home</title>
    </head>
    <body align='center'>
        <div>
            <br><br>
            <a href='http://127.0.0.1:8000/ratings/movies/'><button style="height:75px;width:200px"><font size='3'>Full Movie List</font></button></a>
            <br><br><br><br>
            <a href='http://127.0.0.1:8000/ratings/top/'><button style="height:75px;width:200px"><font size='3'>Top Rated Movies</font></button></a>
            <br><br><br><br>
            <a href='http://127.0.0.1:8000/ratings/raters/'><button style="height:75px;width:200px"><font size='3'>User Information</font></button></a>
            <br><br><br><br>
            {% if is_authenticated %}
            <span>
            <a href="{% url "django.contrib.auth.views.logout" %}?next=/accounts/logout_success/"><button style="height:75px;width:200px"><font size='3'>Logout</font></button></a>
            </span>
            {% else %}
            <span>
            <a href='http://127.0.0.1:8000/login'><button style="height:75px;width:200px"><font size='3'>Login</font></button></a>
            </span>
            <br><br><br><br>
            <span>
            <a href="{% url 'accounts:register' %}"><button style="height:75px;width:200px"><font size='3'>Register Here</font></button></a>
            </span>

            {% endif %}
        </div>
    </body>
</html>

movielens/ratings/templates/ratings/movie_detail.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{{ movie }}</title>
    </head>
    <body align= 'center'>
        <div>
            <span>
                <a href='http://127.0.0.1:8000/ratings/'><button style="height:30px;width:150px"><font size='3'>Home</font></button></a>
            </span>
            <span>
                <a href='http://127.0.0.1:8000/ratings/movies/'><button style="height:30px;width:150px"><font size='3'>Full Movie List</font></button></a>
            </span>
            <span>
                <a href='http://127.0.0.1:8000/ratings/top/'><button style="height:30px;width:150px"><font size='3'>Top Rated</font></button></a>
            </span>
            <span>
                <a href='http://127.0.0.1:8000/ratings/raters/'><button style="height:30px;width:150px"><font size='3'>User Information</font></button></a>
            </span>
            {% if is_authenticated %}
            <span>
                <a href="{% url "django.contrib.auth.views.logout" %}?next=/accounts/logout_success/"><button style="height:30px;width:150px"><font size='3'>Logout</font></button></a>
            </span>
            {% else %}
            <span>
                <a href='http://127.0.0.1:8000/login'><button style="height:30px;width:150px"><font size='3'>Login</font></button></a>
            </span>
            {% endif %}
        </div>
        <hr>

        <h3>You are viewing the full details for: </h3>
        <h1><b><u>{{ movie }}</u></b></h1>

        <table align='center' style="width:33%" border='1'>
            <tr height='30'>
                <th><u>Released</u>:</th>
                <td>{{ movie.release }}</td>
            </tr>
            <tr height='30'>
                <th><u>Website</u>:</th>
                <td><a href={{ movie.url }}><img src="http://movse.tv/wp-content/themes/movse/images/logo-imdb.svg" alt="IMDB" /></a></td>
            </tr>
        </table>

        <br><hr>

        <h2><u><font size='5'>All Ratings</font></u></h2>

        <table align='center' cellpadding='5'>
            <tr align='left' height='25'>
                <th><u>Average Rating</u>:</th>
                <td width='50'>{{ movie.avg_rating }}</td>
                <td align='left'>|</td>
                <th><u>Total Number of Ratings</u>:</th>
                <td width='50'>{{ movie.total_ratings }}</td>
            </tr>
        </table>

        <p>***If you want to see more information on the ratings, simply click the rater's information***</p>

        <table align='center' cellpadding='5' border='1' style='width:15%'>
            <tr>
                <th>Rater</th>
                <th>Score</th>
            </tr>
            {% for rating in ratings %}
            <tr>
                <td><a href="{% url 'ratings:rater_detail' rating.rater_id %}">{{rating.rater_id}}</a></td>
                <td>{{rating.score}}</td>
            </tr>
            {% endfor %}
        </table>
    </body>
</html>

movielens/ratings/templates/ratings/movie_index.html
<html>
  <head>
      <title>Movie Search</title>
  </head>
  <body align='center'>

      <div>
          <span>
              <a href='http://127.0.0.1:8000/ratings/'><button style="height:30px;width:150px"><font size='3'>Home</font></button></a>
          </span>
          <span>
              <a href='http://127.0.0.1:8000/ratings/movies/'><button style="height:30px;width:150px"><font size='3'>Full Movie List</font></button></a>
          </span>
          <span>
              <a href='http://127.0.0.1:8000/ratings/top/'><button style="height:30px;width:150px"><font size='3'>Top Rated</font></button></a>
          </span>
          <span>
              <a href='http://127.0.0.1:8000/ratings/raters/'><button style="height:30px;width:150px"><font size='3'>User Information</font></button></a>
          </span>
          {% if is_authenticated %}
          <span>
          <a href="{% url "django.contrib.auth.views.logout" %}?next=/accounts/logout_success/"><button style="height:30px;width:150px"><font size='3'>Logout</font></button></a>
          </span>
          {% else %}
          <span>
          <a href='http://127.0.0.1:8000/login'><button style="height:30px;width:150px"><font size='3'>Login</font></button></a>
          </span>
          {% endif %}
      </div>
      <hr>

    {% if movies %}

        <h1>Viewing {{ movies|length }} movie{{ movies|pluralize }} matching: <strong>'{{ query  }}'</strong><h1>
        <hr>

        <form action="" method="get">
            <input type="text" name="q">
            <input type="submit" value="Search">
        </form>
        <table align='center' border='1'>
            <tr align='center'>
                {% for header in columns %}
                <td><b>{{ header }}</b></td>
                {% endfor %}
            </tr>
            {% for movie in movies %}
            <tr align='center'>
                <td><a href="{% url 'ratings:movie_detail' movie.id %}">{{ movie.title }}</a></td>
                <td>{{ movie.avg_rating }}</td>
                <td><a href={{ movie.url }}><img src="http://movse.tv/wp-content/themes/movse/images/logo-imdb.svg" alt="IMDB" /></a></td>
            </tr>
            {% endfor %}
        </table>

    {% else %}

    <h1>You are viewing the full list of movies.</h1>
    <p>***If you want to see more information on a movie and its ratings, simply click its title***</p>
    <hr>
    {% if search %}
    <p><font size='4px'>You searched for: <strong><font size='5px'>{{ query  }}</strong></font></font></p>
    <p>No movies matched your search criteria.</p>
    <hr><br>
    {% endif %}
        <form action="/ratings/movies/search/" method="get">
            <input type="text" name="q">
            <input type="submit" value="Search">
        </form>

        <div>
            <table border=1 align='center'>
                <tr>
                    {% for header in columns %}
                    <td><b>{{ header }}</b></td>
                    {% endfor %}
                </tr>
                {% for movie in all_movies %}
                <tr>
                    <td><a href="{% url 'ratings:movie_detail' movie.id %}">{{ movie.title }}</a></td>
                    <td>{{ movie.avg_rating }}</td>
                    <td><a href={{ movie.url }}><img src="http://movse.tv/wp-content/themes/movse/images/logo-imdb.svg" alt="IMDB" /></a></td>
                </tr>
                {% endfor %}
            </table>
        </div>
    {% endif %}

  </body>
</html>

movielens/ratings/templates/ratings/rater_detail.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{{ movie }}</title>
    </head>
    <body align='center'>
        <div>
            <span>
                <a href='http://127.0.0.1:8000/ratings/'><button style="height:30px;width:150px"><font size='3'>Home</font></button></a>
            </span>
            <span>
                <a href='http://127.0.0.1:8000/ratings/movies/'><button style="height:30px;width:150px"><font size='3'>Full Movie List</font></button></a>
            </span>
            <span>
                <a href='http://127.0.0.1:8000/ratings/top/'><button style="height:30px;width:150px"><font size='3'>Top Rated</font></button></a>
            </span>
            <span>
                <a href='http://127.0.0.1:8000/ratings/raters/'><button style="height:30px;width:150px"><font size='3'>User Information</font></button></a>
            </span>
            {% if is_authenticated %}
            <span>
                <a href="{% url "django.contrib.auth.views.logout" %}?next=/accounts/logout_success/"><button style="height:30px;width:150px"><font size='3'>Logout</font></button></a>
            </span>
            {% else %}
            <span>
                <a href='http://127.0.0.1:8000/login'><button style="height:30px;width:150px"><font size='3'>Login</font></button></a>
            </span>
            {% endif %}
        </div>
        <hr>
        <h3 align='center'>You are viewing the full details for: </h3>
        <h1 align='center'><b><u>User {{ rater.id }}</u></b></h1>

        <table align='center' style="width:20%" border='1'>
            <tr align='center' height='25'>
                <th><u>Age</u>:</th>
                <td>{{ rater.age }}</td>
            </tr>
            <tr align='center' height='25'>
                <th><u>Sex</u>:</th>
                <td>{{ rater.sex }}</td>
            </tr>
            <tr align='center' height='25'>
                <th><u>Occupation</u>:</th>
                <td>{{ rater.occupation }}</td>
            </tr>
        </table>
        <br>

        <h2 align='center'><u><font size='5'>All Ratings</font></u></h2>

        <table align='center' cellpadding='5'>
            <tr align='left' height='25'>
                <th><u>Average Rating Given</u>:</th>
                <td align='center' width='50'>{{ rater.avg_rating }}</td>
                <td align='left'>|</td>
                <th><u>Total Number of Ratings</u>:</th>
                <td align='center' width='50'>{{ rater.total_ratings }}</td>
            </tr>
        </table>

        <p align='center'>***If you want to see more information on the ratings, simply click the rater's information***</p>

        <table align='center' cellpadding='5' border='1'>
            <tr>
                <th>Movie</th>
                <th>Score</th>
            </tr>
            {% for rating in ratings %}

            <tr align='center'>
                <td><a href="{% url 'ratings:movie_detail' rating.movie_id %}">{{rating.movie_name}}</a></td>
                <td>{{rating.score}}</td>
            </tr>
            {% endfor %}
        </table>
    </body>
</html>

movielens/ratings/templates/ratings/rater_index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Movies Index</title>
    </head>
    <body align='center'>
        <div>
            <span>
                <a href='http://127.0.0.1:8000/ratings/'><button style="height:30px;width:150px"><font size='3'>Home</font></button></a>
            </span>
            <span>
                <a href='http://127.0.0.1:8000/ratings/movies/'><button style="height:30px;width:150px"><font size='3'>Full Movie List</font></button></a>
            </span>
            <span>
                <a href='http://127.0.0.1:8000/ratings/top/'><button style="height:30px;width:150px"><font size='3'>Top Rated</font></button></a>
            </span>
            {% if is_authenticated %}
            <span>
                <a href="{% url "django.contrib.auth.views.logout" %}?next=/accounts/logout_success/"><button style="height:30px;width:150px"><font size='3'>Logout</font></button></a>
            </span>
            {% else %}
            <span>
                <a href='http://127.0.0.1:8000/login'><button style="height:30px;width:150px"><font size='3'>Login</font></button></a>
            </span>
            {% endif %}
        </div>
        <hr>
        <h1>You are viewing the full list of users.</h1>
        <p>***If you want to see more information on a user and their ratings, simply click their ID***</p>
        <br>
        <div>
            <table border=1 align='center' style='width:50%' cellpadding='4'>
                <tr>
                    {% for header in columns %}
                    <td><b>{{ header }}</b></td>
                    {% endfor %}
                </tr>
                {% for rater in raters %}
                <tr>
                    <td><a href="{% url 'ratings:rater_detail' rater.id %}">{{ rater.id }}</a></td>
                    <td>{{ rater.age }}</td>
                    <td>{{ rater.sex }}</td>
                    <td>{{ rater.occupation }}</td>
                    <td>{{ rater.total_ratings }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </body>
</html>

movielens/ratings/templates/ratings/redirect.html
<html>
  <head>
    <title>IU Webmaster redirect</title>
    <META http-equiv="refresh" content="3;URL={% url 'ratings:redirect' %}">
  </head>
  <body bgcolor="#ffffff">
    <center>THAT IS NOT A VALID ADDRESS. YOU ARE BEING REDIRECTED TO THE HOME PAGE.
    </center>
  </body>
</html>

movielens/ratings/templates/ratings/top_rated.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Top Rated Movies</title>
    </head>
    <body align='center'>
        <div>
            <span>
                <a href='http://127.0.0.1:8000/ratings/'><button style="height:30px;width:150px"><font size='3'>Home</font></button></a>
            </span>
            <span>
                <a href='http://127.0.0.1:8000/ratings/movies/'><button style="height:30px;width:150px"><font size='3'>Full Movie List</font></button></a>
            </span>
            <span>
                <a href='http://127.0.0.1:8000/ratings/raters/'><button style="height:30px;width:150px"><font size='3'>User Information</font></button></a>
            </span>
            {% if is_authenticated %}
            <span>
                <a href="{% url "django.contrib.auth.views.logout" %}?next=/accounts/logout_success/"><button style="height:30px;width:150px"><font size='3'>Logout</font></button></a>
            </span>
            {% else %}
            <span>
                <a href='http://127.0.0.1:8000/login'><button style="height:30px;width:150px"><font size='3'>Login</font></button></a>
            </span>
            {% endif %}
        </div>
        <hr>
        <h1><u>Top 20 movies</u></h1>
        <p>***If you want to see more information on a movie and its ratings, simply click its title***</p>
        <br>
        <table border=1 align='center'>
            <tr>
                {% for header in columns %}
                <td><b>{{ header }}</b></td>
                {% endfor %}
            </tr>
            {% for movie in top_rated %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td><a href="{% url 'ratings:movie_detail' movie.id %}">{{ movie.title }}</a></td>
                <td>{{ movie.avg_rating }}</td>
                <td>{{ movie.total_ratings }}</td>
                <td><a href={{ movie.url }}><img src="http://movse.tv/wp-content/themes/movse/images/logo-imdb.svg" alt="IMDB" /></a></td>
            </tr>
            {% endfor %}
        </table>
    </body>
</html>